blank_issues_enabled: true
contact_links:
  - name: Other support links
    url: https://www.oitswilliam.com/support
    about: Choose here for the other contacting methods in Oitswilliam Pang website.
